- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: java
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: mysql setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mysql-setup

- name: mongodb setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd